### ISSUE TITLE
Memory leak in BootstrapTest+0x5af457

### ISSUE THREAD

**Issue by RootUp** [facebook/wangle#144]
Hi Team,

I used clang 6.0 and ASAN to build wangle and multiple memory leaks was detected in `./wangle/wangle/bin/BootstrapTest` 

This is the ASAN information:
```
==3588==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 264 byte(s) in 11 object(s) allocated from:
    #0 0x7fbabf31a458 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xe0458)
    #1 0x555d68e82457 in TestClientPipelineFactory::newPipeline(std::shared_ptr<folly::AsyncTransportWrapper>) (/home/input0/Desktop/wangle/wangle/bin/BootstrapTest+0x5af457)
    #2 0x555d68f0fde8 in wangle::BaseClientBootstrap<wangle::Pipeline<folly::IOBufQueue&, std::unique_ptr<folly::IOBuf, std::default_delete<folly::IOBuf> > > >::makePipeline(std::shared_ptr<folly::AsyncTransportWrapper>) (/home/input0/Desktop/wangle/wangle/bin/BootstrapTest+0x63cde8)
    #3 0x555d68f0d4eb in wangle::ClientBootstrap<wangle::Pipeline<folly::IOBufQueue&, std::unique_ptr<folly::IOBuf, std::default_delete<folly::IOBuf> > > >::ConnectCallback::connectSuccess() (/home/input0/Desktop/wangle/wangle/bin/BootstrapTest+0x63a4eb)
    #4 0x7fbabeb53b3d in folly::AsyncSocket::invokeConnectSuccess() /home/input0/Desktop/proxygen/proxygen/folly/folly/io/async/AsyncSocket.cpp:2769
    #5 0x7fbabeb508f8 in folly::AsyncSocket::handleConnect() /home/input0/Desktop/proxygen/proxygen/folly/folly/io/async/AsyncSocket.cpp:2281
    #6 0x7fbabeb4f54b in folly::AsyncSocket::handleWrite() /home/input0/Desktop/proxygen/proxygen/folly/folly/io/async/AsyncSocket.cpp:2039
    #7 0x7fbabeb4d7a1 in folly::AsyncSocket::ioReady(unsigned short) /home/input0/Desktop/proxygen/proxygen/folly/folly/io/async/AsyncSocket.cpp:1754
    #8 0x7fbabeb54e7c in folly::AsyncSocket::IoHandler::handlerReady(unsigned short) /home/input0/Desktop/proxygen/proxygen/folly/folly/io/async/AsyncSocket.h:1028
    #9 0x7fbabeb7d440 in folly::EventHandler::libeventCallback(int, short, void*) /home/input0/Desktop/proxygen/proxygen/folly/folly/io/async/EventHandler.cpp:161
    #10 0x7fbaba86fa10  (/usr/lib/x86_64-linux-gnu/libevent-2.1.so.6+0x1ea10)

Direct leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7fbabf318b50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
    #1 0x555d68e6a2f8 in folly::checkedMalloc(unsigned long) /usr/local/include/folly/memory/Malloc.h:228
    #2 0x7fbabeb0453d in folly::IOBuf::operator new(unsigned long) /home/input0/Desktop/proxygen/proxygen/folly/folly/io/IOBuf.cpp:135
    #3 0x7fbabeb0890d in std::_MakeUniq<folly::IOBuf>::__single_object std::make_unique<folly::IOBuf, folly::IOBuf::CreateOp, unsigned long&>(folly::IOBuf::CreateOp&&, unsigned long&) /usr/include/c++/7/bits/unique_ptr.h:825
    #4 0x7fbabeb04cca in folly::IOBuf::createSeparate(unsigned long) /home/input0/Desktop/proxygen/proxygen/folly/folly/io/IOBuf.cpp:269
    #5 0x7fbabeb04aec in folly::IOBuf::create(unsigned long) /home/input0/Desktop/proxygen/proxygen/folly/folly/io/IOBuf.cpp:242
    #6 0x7fbabeb0a772 in folly::IOBufQueue::preallocateSlow(unsigned long, unsigned long, unsigned long) /home/input0/Desktop/proxygen/proxygen/folly/folly/io/IOBufQueue.cpp:214
    #7 0x555d68e6eb04 in folly::IOBufQueue::preallocate(unsigned long, unsigned long, unsigned long) (/home/input0/Desktop/wangle/wangle/bin/BootstrapTest+0x59bb04)
    #8 0x555d68e78271 in folly::AsyncUDPServerSocket::getReadBuffer(void**, unsigned long*) (/home/input0/Desktop/wangle/wangle/bin/BootstrapTest+0x5a5271)
    #9 0x7fbabeb6492e in folly::AsyncUDPSocket::handleRead() /home/input0/Desktop/proxygen/proxygen/folly/folly/io/async/AsyncUDPSocket.cpp:551
    #10 0x7fbabeb6422a in folly::AsyncUDPSocket::handlerReady(unsigned short) /home/input0/Desktop/proxygen/proxygen/folly/folly/io/async/AsyncUDPSocket.cpp:461
    #11 0x7fbabeb7d440 in folly::EventHandler::libeventCallback(int, short, void*) /home/input0/Desktop/proxygen/proxygen/folly/folly/io/async/EventHandler.cpp:161
    #12 0x7fbaba86f8f7  (/usr/lib/x86_64-linux-gnu/libevent-2.1.so.6+0x1e8f7)

Direct leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7fbabf31a458 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xe0458)
    #1 0x555d68e82457 in TestClientPipelineFactory::newPipeline(std::shared_ptr<folly::AsyncTransportWrapper>) (/home/input0/Desktop/wangle/wangle/bin/BootstrapTest+0x5af457)
    #2 0x555d68f0fde8 in wangle::BaseClientBootstrap<wangle::Pipeline<folly::IOBufQueue&, std::unique_ptr<folly::IOBuf, std::default_delete<folly::IOBuf> > > >::makePipeline(std::shared_ptr<folly::AsyncTransportWrapper>) (/home/input0/Desktop/wangle/wangle/bin/BootstrapTest+0x63cde8)
    #3 0x555d68f0d4eb in wangle::ClientBootstrap<wangle::Pipeline<folly::IOBufQueue&, std::unique_ptr<folly::IOBuf, std::default_delete<folly::IOBuf> > > >::ConnectCallback::connectSuccess() (/home/input0/Desktop/wangle/wangle/bin/BootstrapTest+0x63a4eb)
    #4 0x7fbabeb53b3d in folly::AsyncSocket::invokeConnectSuccess() /home/input0/Desktop/proxygen/proxygen/folly/folly/io/async/AsyncSocket.cpp:2769
    #5 0x7fbabeb4699e in folly::AsyncSocket::connect(folly::AsyncSocket::ConnectCallback*, folly::SocketAddress const&, int, std::map<folly::AsyncSocket::OptionKey, int, std::less<folly::AsyncSocket::OptionKey>, std::allocator<std::pair<folly::AsyncSocket::OptionKey const, int> > > const&, folly::SocketAddress const&) /home/input0/Desktop/proxygen/proxygen/folly/folly/io/async/AsyncSocket.cpp:597
    #6 0x555d68e91ef3 in wangle::ClientBootstrap<wangle::Pipeline<folly::IOBufQueue&, std::unique_ptr<folly::IOBuf, std::default_delete<folly::IOBuf> > > >::connect(folly::SocketAddress const&, std::chrono::duration<long, std::ratio<1l, 1000l> >)::{lambda()#1}::operator()() const (/home/input0/Desktop/wangle/wangle/bin/BootstrapTest+0x5beef3)
    #7 0x555d68ebf1fd in void folly::detail::function::FunctionTraits<void ()>::callSmall<wangle::ClientBootstrap<wangle::Pipeline<folly::IOBufQueue&, std::unique_ptr<folly::IOBuf, std::default_delete<folly::IOBuf> > > >::connect(folly::SocketAddress const&, std::chrono::duration<long, std::ratio<1l, 1000l> >)::{lambda()#1}>(folly::detail::function::Data&) (/home/input0/Desktop/wangle/wangle/bin/BootstrapTest+0x5ec1fd)
    #8 0x555d68e8511f in folly::detail::function::FunctionTraits<void ()>::operator()() (/home/input0/Desktop/wangle/wangle/bin/BootstrapTest+0x5b211f)
    #9 0x7fbabeb6b479 in folly::EventBase::runImmediatelyOrRunInEventBaseThreadAndWait(folly::Function<void ()>) /home/input0/Desktop/proxygen/proxygen/folly/folly/io/async/EventBase.cpp:629
    #10 0x555d68e9251f in wangle::ClientBootstrap<wangle::Pipeline<folly::IOBufQueue&, std::unique_ptr<folly::IOBuf, std::default_delete<folly::IOBuf> > > >::connect(folly::SocketAddress const&, std::chrono::duration<long, std::ratio<1l, 1000l> >) (/home/input0/Desktop/wangle/wangle/bin/BootstrapTest+0x5bf51f)
    #11 0x555d68e64c2c in Bootstrap_UnixServer_Test::TestBody() /home/input0/Desktop/wangle/wangle/bootstrap/test/BootstrapTest.cpp:395
    #12 0x555d690d36f2 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/input0/Desktop/wangle/wangle/bin/BootstrapTest+0x8006f2)
    #13 0x555d690cdec0 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/input0/Desktop/wangle/wangle/bin/BootstrapTest+0x7faec0)
    #14 0x555d690b1f0b in testing::Test::Run() (/home/input0/Desktop/wangle/wangle/bin/BootstrapTest+0x7def0b)
    #15 0x555d690b2841 in testing::TestInfo::Run() (/home/input0/Desktop/wangle/wangle/bin/BootstrapTest+0x7df841)
    #16 0x555d690b2ec3 in testing::TestCase::Run() (/home/input0/Desktop/wangle/wangle/bin/BootstrapTest+0x7dfec3)
    #17 0x555d690b9d8f in testing::internal::UnitTestImpl::RunAllTests() (/home/input0/Desktop/wangle/wangle/bin/BootstrapTest+0x7e6d8f)
    #18 0x555d690d4750 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (/home/input0/Desktop/wangle/wangle/bin/BootstrapTest+0x801750)
    #19 0x555d690cec36 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (/home/input0/Desktop/wangle/wangle/bin/BootstrapTest+0x7fbc36)
    #20 0x555d690b8953 in testing::UnitTest::Run() (/home/input0/Desktop/wangle/wangle/bin/BootstrapTest+0x7e5953)
    #21 0x555d68f4876c in RUN_ALL_TESTS() /usr/local/include/gtest/gtest.h:2233
    #22 0x555d68f486b2 in main /home/input0/Desktop/wangle/wangle/test/TestMain.cpp:30
    #23 0x7fbabbe22b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
....
SUMMARY: AddressSanitizer: 19284 byte(s) leaked in 172 allocation(s).
```

Please refer to [memoryleak.txt](https://github.com/facebook/wangle/files/2761077/memoryleak.txt) for full ASAN leaks.

**Comment by RootUp** [comment]
Ping @cdelahousse

Could you please look into this ?
